### ISSUE TITLE
[Feature Request] 3D sbs video depthmap support (move left and right meshes/depthmaps to same position in Unity coordinate space for enhanced 3D? Using only left eye texture for both meshes)

### ISSUE THREAD

**Issue by brentjohnston** [parkchamchi/DepthViewer#10]
while I was using this app I was thinking about how the monoscopic to VR video conversion works so well in this even with just Midas, Beit and Marigold being mindblowing. [follow this post](https://github.com/parkchamchi/DepthViewer/issues/5#issuecomment-1657791622)

If we were to add 3D side-by-side VR180 video support with the realtime depthmaps (and marigold if if ever magically gets optimized for realtime) would this allow for VR180 videos with better 3D and postitional tracking? 

I just loaded a VR video from my VR180 camera and the left and right side appear and has depthmaps on both sides, it just needs to be combined into one image somehow. This could make for a much more comfortable and immersive viewing experience due to the 3D being better from the side by side image having more views.

I've realized this app actually does have 6dof positional tracking for the headset, the problem was the objects are so large and far away that it feels like 3dof, (Edit: the VR camera is very far away by default) Is there no way to physically move forward, backwards in the space?

**Comment by parkchamchi** [comment]
Sorry, I don't get what you mean by "3D side-by-side VR180 video support ". Is it about 180 deg video, but with no depth information? So the program can add inferred depth to it? In that case, one can generate a (hemi-)sphere mesh and then displacing the vertices.

**Comment by brentjohnston** [comment]
I am saying I can load a 180 degree 3d sbs video into depthviewer at the moment is shows the video monoscopically with the left part of video on left and part of video video on the right, and using depthmap with beit, I can see if creates 3d for both sides.

The idea is to somehow to combine the left and right image and left and right depthmaps into one image, so that the 3D is much enhanced over just a simple monoscopic to 3D conversion. And it will have full positional tracking also with increase accurate 3d volume due to the left and right images being combined.

 I was able to fix the scale and distance issue I had with this program by using openvradvanced settings and forcing the playspace offset settings after shrinking everything. So we could get very accurate and to scale 3d sbs video, of course faster using dpt hybrid, I just love the accurate 3d a beit when pausing.

**Comment by brentjohnston** [comment]
![DepthViewer-3dsbs](https://github.com/parkchamchi/DepthViewer/assets/23625562/e3ed141e-24af-4d99-9325-c7fb0f2bb1b7)

I tried to break it down in an image to easier understand, The only side effect I could image is that left and right eye texture would combine in the Unity coordinate space, and it maybe wouldnt look right. I can't really image it yet until I try it, but of course this idea wouldnt work for regular 3D monitor/3D glasses users. 

But for VR, If a texture from only the left eye were overlayed on both the left and right eye's orginal depthmap meshes, I wonder if that would increase the 3D volume also, since there is more depthmap mesh volume then.

**Comment by parkchamchi** [comment]
It's an interesting approach, though I still don't fully get it 😅 Sorry. But it's about 6DoF, right?
I'd put here some related points:

- The side-by-side (or top-and-bottom) 3D videos have ground-truth depth -- [repos like this](https://github.com/pairote/stereo2depth) demonstrates it can be extracted as depth maps -- without ML models but with simple CV operations.
- On ML models like MiDaS, SBS images works less efficient than just single image, since there are unrelated images concatenated.
- "Overlaying" the mesh can not be trivial in this repo.
- The post-processing of videos can be done on the python servers: like [this one](https://github.com/parkchamchi/DepthViewer/blob/master/DEPTH/depthpy/ffpymq.py).
- 180 or 360 deg videos would look better on a sphere mesh.

**Comment by brentjohnston** [comment]
Yes it's for enhancing 6dof. Yes I use sphere mesh in programs like DEO player but thinking more about adding positional tracking to the 3d sbs vr videos. I think I will focus on on fixing the Unity project for now so I don't bug you with these ideas, but these are all good points you have here to consider.
