### ISSUE TITLE
Onnxruntime errors on startup of Unity Project

### ISSUE THREAD

**Issue by brentjohnston** [parkchamchi/DepthViewer#12]
I noticed the onnxruntime .dll files show 3 errors by default when you open this project in Unity, and are not set to "load on startup" so I selected all the onnxruntime dll files under \DEPTH\Assets\Plugins\OnnxRuntimeDlls\win-x64 and set load on startup.

They try to load now but there are 4 new errors I highlighted for all of them about "expected x64 architecture, but was Unknown architecture. You must recompile your plugin for x64 architecture." I am using 64 bit Unity version 2021.3.10f1 I have tried on two separate systems and same errors.

![error](https://github.com/parkchamchi/DepthViewer/assets/23625562/35ca46db-5944-49cb-a5d6-62046e3c7c6a)

I tried to change the any platform and platform settings for the .dll but it makes no difference.

**Comment by parkchamchi** [comment]
That's weird, 
- Does the build version of the program can run OnnxRuntime?
- Can you try other versions of OnnxRuntime dlls - as [here](https://github.com/parkchamchi/DepthViewer#onnx-runtime-dll-files)?

**Comment by brentjohnston** [comment]
Yes build version works great, I just used beit model with onnx Cuda setting. I even tried replacing all the .dll files for the Unity the project and used dependencies program to analyze, they are all 64 bitt, but always the same error.

**Comment by parkchamchi** [comment]
This is *really* weird. To test furthermore I suggest you delete all other dll files other than `Microsoft.ML.OnnxRuntime.dll`, which is a wrapper of actual native library. Just to clear it out, since the other ones are not needed to build the program.

- Can you check `git --diff` to see if there is any differences between the master?
- Can you check the MD5 (or SHA-256) hash of the dll file?
- Can you try switching `Microsoft.ML.OnnxRuntime.dll` with other ones in [here](`Microsoft.ML.OnnxRuntime.dll`), like the one in `netstandard2.0`?

If none works just remove the dll files and comment out `using Microsoft.ML.OnnxRuntime...` and the code inside all subroutines in `OnnxRuntimeDepthModelBehavior.cs` to skip this issue.

**Comment by brentjohnston** [comment]
Could this be why? I didn't notice this error before when git cloning (wasn't paying attention after I cloned) 
![error](https://github.com/parkchamchi/DepthViewer/assets/23625562/15d2b57c-6526-474f-936a-5deda740bbdd) I'm not sure what this means or what to do.

**Comment by brentjohnston** [comment]
Update: I could only compare the sha256 because that's all I can see on github, they are indeed different. The release build also doesn't have the Microsoft.ML.OnnxRuntime.dll at all in plugins/onnxruntime folder.

![compare1](https://github.com/parkchamchi/DepthViewer/assets/23625562/1dfb76fb-1092-4bfe-b0a1-d26c2f2ea1b3)

![compare2](https://github.com/parkchamchi/DepthViewer/assets/23625562/413b3ef3-117d-488b-8d78-5db2bf4b9f76)

**Comment by brentjohnston** [comment]
I think there may be a problem now with the 202kb Microsoft.ML.OnnxRuntime.dll file I used, can't load custom models now after I build, they show up in the list but it gives this error in console after clicking load:

![modelload-issue](https://github.com/parkchamchi/DepthViewer/assets/23625562/cb1c5b21-005b-418a-98c7-78c734179283)

**Comment by parkchamchi** [comment]
Yup, my Git LFS bandwith was full (1.7GB out of 1GB), so you would get corrupted dll files -- which Unity could not parse.

>I have tried downloading the file separately like you said though but the only file present in the Microsoft.ML.OnnxRuntime.DirectML.1.16.3.nuget (renamed to .zip and extract) \build\netstandard2.0 is Microsoft.ML.OnnxRuntime.DirectML.props

You are not meant to download `.DirectML`, what is needed is `.Gpu` and `.Managed`. `.Gpu` is actual native libraries and `.Managed` is the C# binding. [More info here](https://github.com/parkchamchi/DepthViewer#onnx-runtime-dll-files)

>I think there may be a problem now with the 202kb Microsoft.ML.OnnxRuntime.dll file I used, can't load custom models now after I build, they show up in the list but it gives this error in console after clicking load:

Are `onnxruntime.dll`, `onnxruntime_providers_shared.dll`, `onnxruntime_providers_cuda.dll` present in the `Plugins/`? The are not needed for the build but are the actual native libraries.

**Comment by brentjohnston** [comment]
I was just able to resolve this 10 minutes ago using microsoft.ml.onnxruntime.managed.1.12.0.nuget it was the only file I could find that has the lib folder and the a 130kb Microsoft.ML.OnnxRuntime.dll file. 

It's working now! The ones I tried in the readme though in plugins folder did not have the Microsoft.ML.OnnxRuntime.dll file anymore.
