### ISSUE TITLE
Errors when clone repo (not just lfs storage past quota problem)

### ISSUE THREAD

**Issue by brentjohnston** [parkchamchi/DepthViewer#15]
I have noticed whenever I try to clone the repo I run into errors in the Unity Project on startup. I actually fixed them in an older local build here, but forgot exactly what I did and hoping to find some clarification.

For the lfs storage being past quote (and not downloading the onnxruntime files fully) I just [copy and paste the onnxruntime .dlls](https://github.com/parkchamchi/DepthViewer/issues/12) from my working project for now. But when I start it up I am getting plasticSCM, lib_burst_generated.dll being copied twice errors (deleting duplicates of lib_burst_generated.dll, deleting library and temp folders, did not resolve) 

I think I had to turn off `enable burst compilation` in project settings > burst aot settings, but not sure if there's a consequence to that. The plasticSCM error I also just got rid of again somehow (I think I may have updated in the package manager but not sure) but these errors are present each time I clone repo. Any ideas?

**Comment by parkchamchi** [comment]
Disabling the burst compilation would not make any difference outside the build performance, I think. PlasticSCM is the weird one, for me it appears when any DLL file is changed but disappears when the editor is reloaded. Maybe related to the .NET framework version?

**Comment by brentjohnston** [comment]
Thanks for the info! Also not sure if you can check the marigold issues post but I feel like I'm getting fairly close to getting the depth-anything model working but doing something wrong, or I'm not close and way off :)
