### ISSUE TITLE
slideshow?

### ISSUE THREAD

**Issue by b4nn3d** [parkchamchi/DepthViewer#16]
hello there :)
can you implement a simple slideshow when opening a folder?

**Comment by parkchamchi** [comment]
Would signaling "next" (like the scroll wheel down) periodically by set seconds fit for your purpose?

**Comment by b4nn3d** [comment]
yes, a very simple slideshow. 
maybe you can just add another checkbox within the 'shuffle' and 'include gif files' ones :)

**Comment by parkchamchi** [comment]
I've put commands `sshow 1` and `sshow_end` for automatic scrolling.
