### ISSUE TITLE
depth.py in Windows (CR LF) format (affects depth-anything script from working)

### ISSUE THREAD

**Issue by brentjohnston** [parkchamchi/DepthViewer#18]
I created a new issue because I found a problem, the depth.py from the beta6 release shows Windows (CR LF) format, while the one in the working beta6 build for Depth-anything from Threedeejay shows Unix (LF) format (check bottom right of Notepad++ images). The scripts are identical besides that. (I think the number of lines difference reported is from a big square block being created throwing it off which you'll see) This does not affect Marigold in the script, but affects Depth-anything.

![threedeejay-beta6](https://github.com/parkchamchi/DepthViewer/assets/23625562/4cc4b472-d53d-4c2d-a282-4bf42934b164)
![release-build](https://github.com/parkchamchi/DepthViewer/assets/23625562/bd978721-4d83-4dc1-b0c9-fc1dc626b1fc)

When I compare side by side something is happening at line 611 when it is in the default Windows CR LF format from the .zip files beta release. This small difference in format makes the script not work. 
![compare](https://github.com/parkchamchi/DepthViewer/assets/23625562/62bc0b56-537a-41c0-ba3b-ecad0ea23446)

It was downloaded through firefox and I thought maybe it's changing the contents in the zip files somehow, but I also tried `curl -L -o DepthViewer-v0.9.1-beta.6-win64.7z https://github.com/parkchamchi/DepthViewer/releases/download/v0.9.1-beta.6/DepthViewer-v0.9.1-beta.6-win64.7z` and was same results I also thought maybe winrar is changing it, but I tried 7zip and it's still Windows (CR LF).

I also tried:
1. Open the file in Notepad++.
2. Go to Edit > EOL Conversion > UNIX/OSX Format.
3. Save the file.

But it seems like that doesn't work either because it's still showing a line difference and seems to have corrupted the file metadata already, so simply converting doesn't work. Not sure how threedeejay got a working copy in Unix (LF) format by default. Here are the two scripts if anyone can figure this out. The only fix is if I overwrite the depth.py in the release beta 6 with the unix (lf) format depth.py.

depth.py directly extracted from DepthViewer-v0.9.1-beta.6-win64.7z 
[depth.zip](https://github.com/parkchamchi/DepthViewer/files/14069671/depth.zip)

depth.py threedog beta 6 version he extracted from DepthViewer-v0.9.1-beta.6-win64.7z (I believe)
[depththreedeejay-beta6.zip](https://github.com/parkchamchi/DepthViewer/files/14069680/depththreedeejay-beta6.zip)

Edit: Threedeejay said he over overwrote with this unreleased version he thinks, https://codeload.github.com/parkchamchi/DepthViewer/zip/refs/heads/master I downloaded it and the depth.py is indeed in Linux LF format there, so it works. (cloning report shows Windows CR LF format.)

**Comment by parkchamchi** [comment]
I don't get this one, why would having CRLF rather than LF (or vice versa) would impact the python execution?

There can be an inconsistency because in my environment (win64) the scripts have CRLF, and when I make a release I move my files using a script to the archive, so you'd have CRLF if you unzipped the release. But since -- IIRC -- my git has `autocrlf` on, you'd have LF if you got the scripts from `git`. But I believe it would have no difference in Python.

What I hypothesize is that the CRLF one is from the release, while the "unreleased" LF one is from the master branch. The CRLF version just does not have the reference to the `dany` and it is not the newline issue.

**Comment by brentjohnston** [comment]
Yup you're hypothesis was correct, I have no idea why it said the code was exactly the same between the two files with the programs I was running. Thanks!
