### ISSUE TITLE
Depth images with high dynamic range (high precision)

### ISSUE THREAD

**Issue by nedsed** [parkchamchi/DepthViewer#2]
Hi, great software!

I noticed that all depth data in files is only 8 bits per channel. Would it be possible to optionally use higher precision for export? PNG, for example, can store 32 bits per color. TIFF or OpenEXR could also be used. Gimp unfortunately doesn't support high dynamic range as far as I know, but Photoshop or Blender will do. 8-bit can introduce artifacts when used as a displacement map for rendering.

Best regards!

**Comment by parkchamchi** [comment]
Unity appears to provide the [`EncodeToEXR`](https://docs.unity3d.com/ScriptReference/ImageConversion.EncodeToEXR.html) method in addition to the [`EncodeToPNG` this program is using](https://github.com/parkchamchi/DepthViewer/blob/v0.8.8-beta-prerelease-2/DEPTH/Assets/Scripts/UI/OptionsBehavior.cs#L217), and it supports 16bit or 32bit floating point values. Other formats would require additional libraries. I'll add the EXR export on the future release.

**Comment by nedsed** [comment]
Wonderful, I'm looking forward to it. Thank you very much!

**Comment by parkchamchi** [comment]
Commit 3a127d8 adds the EXR export.

**Comment by parkchamchi** [comment]
Release [v0.8.8](https://github.com/parkchamchi/DepthViewer/releases/tag/v0.8.8) includes this.

**Comment by nedsed** [comment]
I tested it and it works perfectly. Thank you very much!
