### ISSUE TITLE
[Feature Request] implementing new Python Library for Auto1111/Stable diffusion (Unity GUI)

### ISSUE THREAD

**Issue by brentjohnston** [parkchamchi/DepthViewer#20]
There is a new python library/sdk that released that could potentially allow for implementing AI image generation and prompting into depthviewer (with some added GUI elements and code added to Unity of course) https://github.com/saketh12/Auto1111SDK

The dev said on reddit they plan on adding animatediff support for the AI video clips, and bringing automatic1111 extensions. This would mean there would be no need to install automatic1111 separately or using the automatic1111 --api flag

Implementing this in depthviewer could potentially allow for generating AI content from within the app, and then have it convert with depth-anything or marigold immediately, could be pretty mindblowing. Perhaps they could even add stable diffusion video support in the future.

I opened an issue over there to ask the specifics on if it would be possible. Just putting this feature request in, I feel it would really enhance the capabilities of the app. (If it's feasable with what they released)

**Comment by ricardofeynman** [comment]
@brentjohnston Have you heard of this? https://github.com/GothaB/aiimages

**Comment by brentjohnston** [comment]
Very neat I will also check this out, closing issue for now.

**Comment by ricardofeynman** [comment]
@brentjohnston If you have any success fusing the two projects, I'd appreciate an update. Gave it a shot myself previously but I was too busy with other work to give it the required attention. Unfortunately I'm still swamped with other tasks but it's been on my to-do list for months now. GothaB/Sunija has moved on to maintaining an InvokeAI AIO offline installer, but unless something else has slipped under the radar in the last year, this is still the most solid base available for Unity focused in-app AI gens.
