### ISSUE TITLE
Error with "browse files" button in new Unity version 2022.3.18f1 beta project.

### ISSUE THREAD

**Issue by brentjohnston** [parkchamchi/DepthViewer#22]
Very happy with the update as this allows me to implement new depth-api support from meta for hand occlusion. (similar to how apple vision pro does it with hands to blocking virtual objects)

The only issues I have is in play mode with the editor if I click browse button in the GUI I I have this error now:

```
NullReferenceException: Object reference not set to an instance of an object
MainBehavior.BrowseFiles () (at Assets/Scripts/MainBehavior.cs:598)
UnityEngine.Events.InvokableCall.Invoke () (at <f7237cf7abef49bfbb552d7eb076e422>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <f7237cf7abef49bfbb552d7eb076e422>:0)
UnityEngine.UI.Button.Press () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:70)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:114)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:57)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:272)
UnityEngine.EventSystems.EventSystem:Update() (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:530)
```
Not too sure how to fix this.

**Comment by brentjohnston** [comment]
I did a null check with ```
public void BrowseFiles() {
    if (_fileSelecter == null) {
        Debug.LogError("_fileSelecter is not initialized.");
        return;
    }
    _fileSelecter.SelectFile((path) => {
        ClearBrowseDir();
        SelectFile(path);
    });
}

```

and have this error in console in play mode now after clicking browse:

```
_fileSelecter is not initialized.
UnityEngine.Debug:LogError (object)
MainBehavior:BrowseFiles () (at Assets/Scripts/MainBehavior.cs:599)
UnityEngine.EventSystems.EventSystem:Update () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:530)
```

**Comment by brentjohnston** [comment]
I believe all of my issues were related to the initcmd.txt file located in C:\Users\NewPC\AppData\LocalLow\parkchamchi\DepthViewer now that I have deleted that and started a new project it seems to be working now.

**Comment by parkchamchi** [comment]
That's weird, which command in it had probably caused it?

**Comment by brentjohnston** [comment]
For some reason only when running threedeejay's script when I want to use marigold it always puts a new initcmds.txt in C:\Users\NewPC\AppData\LocalLow\parkchamchi\DepthViewer, it contains only the 

```
set_zmq_fail_tol 1000000
set_zmq_timeout 1000000
zmq_id 5556
```

It seems like when trying to run depthviewer when the zmq server isn't running it was creating some issues. When I delete that file in locallow then evreything works.
