### ISSUE TITLE
New versions won't work in desktop mode for me (not sure what changed on my system)

### ISSUE THREAD

**Issue by brentjohnston** [parkchamchi/DepthViewer#23]
Here is a video of the issue I am encountering. Hard hangs on startup for build releases, it also does this in VR mode. Only the old version at the end of video works. 

Any ideas? The old 0.91 used to work fine last week, I imagine 0.10 works for everyone also, the only things that have changed on my system is meta v62 update but I don't see how this would affect desktop mode like this?

https://github.com/parkchamchi/DepthViewer/assets/23625562/c94e0c36-85c2-4a42-9348-1c63dff52ebe

**Comment by brentjohnston** [comment]
I figured it out, had to delete initcmd.txt under C:\Users\NewPC\AppData\LocalLow\parkchamchi\DepthViewer

**Comment by parkchamchi** [comment]
Do you by chance still have `initcmd.txt`?

**Comment by brentjohnston** [comment]
For some reason only when running threedeejay's script when I want to use marigold it always puts a new initcmds.txt in C:\Users\NewPC\AppData\LocalLow\parkchamchi\DepthViewer, it contains only the 

```
set_zmq_fail_tol 1000000
set_zmq_timeout 1000000
zmq_id 5556
```

It seems like when trying to run depthviewer when the zmq server isn't running it was creating some issues if it had put that file there. When I delete that file in locallow then everything works.
