### ISSUE TITLE
Caching not sequential

### ISSUE THREAD

**Issue by ThatDocBoi** [parkchamchi/DepthViewer#25]
I'm not sure if I'm missing an option but the player skips many frames per run as opposed to converting each frame in a row, making it so the video has to be replayed multiple times just to have it fully cached. Any way to make it convert each frame in sequence for depthanything please?

Thank you.

**Comment by parkchamchi** [comment]
Caching on the Unity side (which I consider to be a legacy code at this point) was not meant to process all frames at once. There exists a python script to make such cache file on [`depthpy/`](https://github.com/parkchamchi/DepthViewer/tree/master/DEPTH/depthpy): [`depth.py`](https://github.com/parkchamchi/DepthViewer/blob/master/DEPTH/depthpy/depth.py).

**For default `dpt_hybrid_384`**
```
python depth.py the_input.webm the_output.depthviewer
```

**For depth-anything**
- Get `dany/`:
```cmd
git clone https://github.com/LiheYoung/Depth-Anything
rename Depth-Anything dany
```
- Run
```
python depth.py the_input.webm the_output.depthviewer -r dany -t vitb14
```

**Comment by ThatDocBoi** [comment]
Thanks, this seems to be working. Any chance to make it use the GPU (AMD) as well like the player as it's running at around 0.17 fps?
