### ISSUE TITLE
Error Issues for opening and setting up the project file.

### ISSUE THREAD

**Issue by jhxr01** [parkchamchi/DepthViewer#4]
Hello Sir or Madam.

I am a beginner developer new to using MiDas.

I found your marvelous work during my current research.

But, I also found some missing files(suchas Generated, TextMesh Pro, UserSettings)
![Missing_Files_001](https://github.com/parkchamchi/DepthViewer/assets/138554040/927b0761-c04e-496f-bf68-623e0c2dfd7f)

and there some problems when unity reads dll files.
![Errors_001](https://github.com/parkchamchi/DepthViewer/assets/138554040/9c34729d-96bd-47b6-878a-8ddb29b95eca)

I am wondering if you can guide me how to set your the most current project file in unity properly.

That will be very helpful.

Thank you for reading.

Kind Regards
jhxr

**Comment by parkchamchi** [comment]
1. Most `.meta` warnings are ignorable and will disappear when you reopen the Editor, maybe except the `TextMesh Pro` one. You may have to click the `Import TMP essentials` button on `TMP import` window,
2. The `unityplastic` errors disappears when the Editor is reopen for my case, tell me if this is not in your environment.
3. The `ML` and `InferenceSession` errors occurs when it could not load [OnnxRuntime Managed DLL](https://github.com/parkchamchi/DepthViewer/blob/master/DEPTH/Assets/Plugins/OnnxRuntimeDlls/win-x64/Microsoft.ML.OnnxRuntime.dll). I believe it would disappear when the `unityplastic` errors are gone, but if it's not the case, tell me. The DLL files are included in the repo with Git LFS, so please check if the DLL files actually exist. [If you're not using Windows, the Linux `.so` files would be needed to be prepared manually](https://github.com/parkchamchi/DepthViewer#onnx-runtime-dll-files). 
4. The last `Windows.Forms` error: This seem to be related to the `unityplastic` error. The `Windows.Forms` is only used in [this](https://github.com/parkchamchi/DepthViewer/blob/master/DEPTH/Assets/Scripts/OnlineTex/DesktopRenderBehavior.cs) *deprecated* script, so if this error persists even when the `unityplastic` error is gone, you can disable this script (by making the codes in `#if ...` ineffective). Also, the `Windows.Forms` only works when .NET is `.NET Framework` not `.NET Framework 2.1`, as seen in the `Build Settings`.

If there's any question feel free to ask me.

**Comment by jhxr01** [comment]
Thank you for your prompt response.

I think the error keeps occurring because of No 'git' executables was found

please refer to the attachment.

I kept reopening the project but Unity is telling me the same issue :/

[image: 78c23116-7aed-4cc9-9ae5-cd3c38922978.jpg]


2023년 7월 4일 (화) 오후 3:58, Chanjin Park ***@***.***>님이 작성:

**Comment by jhxr01** [comment]
here is the attachment
![git_Issue](https://github.com/parkchamchi/DepthViewer/assets/138554040/55b24494-6759-4ed6-abed-ed2a0eeb312f)

**Comment by parkchamchi** [comment]
Thank you for your kind words :)
